__include__: [
  '/home/fengrenchen/Code/DEIM-new/configs/yam_config/HomeObeject_detection.yml',
  '../runtime.yml',
  '../base/dataloader_dfine.yml',
  '../base/optimizer.yml',
  '../base/dfine_hgnetv2.yml',
]


checkpoint_freq: 200
print_freq: 400
output_dir: ./outputs/HomeObject_EMFM_pre


model: DEIM_MG

DEIM_MG:
  yaml_path: 
  pretrained: 

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.0004
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.0004
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0008
  betas: [0.9, 0.999]
  weight_decay: 0.0001



# Increase to search for the optimal ema
epoches: 200 # 148 + 4n
train_dataloader:
  total_batch_size: 4
  dataset:
    transforms:
      policy:
        epoch: 188
  collate_fn:
    stop_epoch: 188
    ema_restart_decay: 0.9999
    base_size_repeat: ~

val_dataloader:
  total_batch_size: 4
